#!/bin/sh
set -e

patchdir="debian/patches"
metadir="debian/metapatches"
seriesfile="${patchdir}/series"
prefix="p/"
pext=".patch"

dh_testdir
echo -n '' > $seriesfile
i=1
for metafile in ${metadir}/*
do
    patchname=$(basename $metafile)
    branch=$(sed -n 's/X-git-branch: *\(.*\)$/\1/p' $metafile)
    outfile=${patchdir}/${patchname}${pext}
    i=$(expr ${i} + 1)
    echo $outfile
    rm -f ${outfile}
    cat $metafile > $outfile
    echo "---" >> $outfile
    git diff -p --stat upstream..${branch} >> $outfile
    echo ${patchname}${pext} >> $seriesfile
done
